---
- name: create user
  hosts: redhat-01
  tasks:
    - name: create user
      user:
        name: devops2
        shell: /bin/bash
        groups: wheel
        append: true
        state: absent
